server:
  port: 8082
spring:
  http:
    encoding:
      charset: utf-8
      enabled: true
  mail:
    username: xxxxxxxxxx@qq.com
    password: mmzsblogtest
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true




