#server:
#  port: 18001
#
## spring的相关配置
#spring:
#  application:
#    name: tomcat-jdbc测试
#  # 数据源的配置
#  datasource:
#    # mysql驱动包
#    driver-class-name: com.mysql.jdbc.Driver
#    # mysql数据库 地址；账户；密码
#    url: jdbc:mysql://localhost:3306/mmzsblogtest
#    username: root
#    password: 123456
#
#mybatis:
#  # mapper映射文件
#  mapper-locations: classpath:mapper/*Mapper.xml
#
